spring:
  application:
    name: vaudoise-api-factory
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: vaudoise_password
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.vaudoise.api_factory: DEBUG
