spring:
  application:
    name: vaudoise-api-factory
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    out-of-order: false
server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.vaudoise.api_factory: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    syntaxHighlight:
      activated: true
  show-actuator: true
  paths-to-match: /**
  paths-to-exclude: /actuator/**
